# Generated by Django 2.0.4 on 2018-04-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyboard_name', models.CharField(max_length=50)),
                ('mouse_name', models.CharField(max_length=50)),
                ('monitor_name', models.CharField(max_length=50)),
                ('phone_name', models.CharField(max_length=50)),
            ],
        ),
    ]
