# Generated by Django 2.0.4 on 2018-04-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0002_auto_20180427_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='book_management.Category'),
        ),
    ]
